import React from 'react';
import { ResponsiveContainer, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, Radar, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid } from 'recharts';
import { AlertCircle, CheckCircle, Download, Share2 } from 'lucide-react';

// Mock Data
const skillData = [
  { subject: 'Technical', A: 85, fullMark: 100 },
  { subject: 'Communication', A: 65, fullMark: 100 },
  { subject: 'Confidence', A: 70, fullMark: 100 },
  { subject: 'Problem Solving', A: 90, fullMark: 100 },
  { subject: 'Resume Alignment', A: 50, fullMark: 100 },
  { subject: 'Cultural Fit', A: 75, fullMark: 100 },
];

const confidenceData = [
  { name: 'Intro', confidence: 90 },
  { name: 'Tech Q1', confidence: 85 },
  { name: 'Tech Q2', confidence: 40 },
  { name: 'Behavioral', confidence: 60 },
  { name: 'Closing', confidence: 80 },
];

const Reports: React.FC = () => {
  return (
    <div className="bg-slate-950 min-h-screen py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-7xl mx-auto space-y-8">
        
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center justify-between border-b border-slate-800 pb-6">
          <div>
             <h1 className="text-3xl font-bold text-white">Interview Report #8821X</h1>
             <p className="text-slate-400 text-sm mt-1">Generated by Zelvora AI • Oct 24, 2023</p>
          </div>
          <div className="flex gap-3 mt-4 md:mt-0">
             <button className="flex items-center px-4 py-2 bg-slate-800 hover:bg-slate-700 rounded text-sm text-white transition-colors">
                <Share2 className="h-4 w-4 mr-2"/> Share
             </button>
             <button className="flex items-center px-4 py-2 bg-emerald-600 hover:bg-emerald-700 rounded text-sm text-white transition-colors">
                <Download className="h-4 w-4 mr-2"/> PDF Export
             </button>
          </div>
        </div>

        {/* Verdict Card */}
        <div className="bg-slate-900 border border-slate-800 rounded-lg p-6">
           <h2 className="text-lg font-semibold text-white mb-4">Final Verdict</h2>
           <div className="flex items-start gap-4">
              <div className="p-3 bg-yellow-500/10 rounded-full">
                 <AlertCircle className="h-8 w-8 text-yellow-500" />
              </div>
              <div>
                 <h3 className="text-2xl font-bold text-yellow-500">Waitlist / Second Review</h3>
                 <p className="text-slate-300 mt-2 max-w-4xl">
                    Candidate demonstrates strong technical aptitude in core algorithms but lacked clarity in system design articulation. Confidence dropped significantly during the "Scalability" segment. Resume alignment is partial; some listed projects were not explained in depth.
                 </p>
                 <div className="mt-4 inline-block bg-slate-950 px-3 py-1 rounded border border-slate-800 text-xs font-mono text-slate-500">
                    HIRE_PROBABILITY: 58%
                 </div>
              </div>
           </div>
        </div>

        {/* Charts Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            {/* Skill Radar */}
            <div className="bg-slate-900 border border-slate-800 rounded-lg p-6">
                <h3 className="text-white font-semibold mb-6">Competency Map</h3>
                <div className="h-80 w-full">
                    <ResponsiveContainer width="100%" height="100%">
                        <RadarChart cx="50%" cy="50%" outerRadius="80%" data={skillData}>
                            <PolarGrid stroke="#334155" />
                            <PolarAngleAxis dataKey="subject" tick={{ fill: '#94a3b8', fontSize: 12 }} />
                            <PolarRadiusAxis angle={30} domain={[0, 100]} tick={false} axisLine={false} />
                            <Radar
                                name="Candidate"
                                dataKey="A"
                                stroke="#10b981"
                                strokeWidth={2}
                                fill="#10b981"
                                fillOpacity={0.3}
                            />
                        </RadarChart>
                    </ResponsiveContainer>
                </div>
            </div>

            {/* Confidence Flow */}
            <div className="bg-slate-900 border border-slate-800 rounded-lg p-6">
                <h3 className="text-white font-semibold mb-6">Confidence & Tone Analysis</h3>
                <div className="h-80 w-full">
                    <ResponsiveContainer width="100%" height="100%">
                        <BarChart data={confidenceData} margin={{ top: 20, right: 30, left: 20, bottom: 5 }}>
                            <CartesianGrid strokeDasharray="3 3" stroke="#334155" vertical={false} />
                            <XAxis dataKey="name" stroke="#94a3b8" fontSize={12} tickLine={false} />
                            <YAxis stroke="#94a3b8" fontSize={12} tickLine={false} />
                            <Tooltip 
                                contentStyle={{ backgroundColor: '#020617', borderColor: '#1e293b', color: '#f8fafc' }}
                                cursor={{ fill: '#1e293b', opacity: 0.4 }}
                            />
                            <Bar dataKey="confidence" fill="#3b82f6" radius={[4, 4, 0, 0]} barSize={40} />
                        </BarChart>
                    </ResponsiveContainer>
                </div>
                <p className="text-xs text-slate-500 mt-4 text-center">
                    Detected via vocal tonality and micro-expressions.
                </p>
            </div>
        </div>

        {/* Detailed Feedback List */}
        <div className="bg-slate-900 border border-slate-800 rounded-lg overflow-hidden">
            <div className="px-6 py-4 border-b border-slate-800">
                <h3 className="font-semibold text-white">HR Key Observations</h3>
            </div>
            <div className="divide-y divide-slate-800">
                 <div className="px-6 py-4 flex gap-4">
                     <CheckCircle className="h-5 w-5 text-emerald-500 flex-shrink-0 mt-0.5" />
                     <div>
                         <p className="text-slate-200 text-sm font-medium">Strong React Knowledge</p>
                         <p className="text-slate-400 text-xs mt-1">Correctly identified the reconciliation process and useEffect dependencies.</p>
                     </div>
                 </div>
                 <div className="px-6 py-4 flex gap-4">
                     <AlertCircle className="h-5 w-5 text-red-500 flex-shrink-0 mt-0.5" />
                     <div>
                         <p className="text-slate-200 text-sm font-medium">Resume Discrepancy</p>
                         <p className="text-slate-400 text-xs mt-1">Candidate listed "Lead Architect" for a university project but described role as "Contributor". AI detected inconsistency.</p>
                     </div>
                 </div>
                 <div className="px-6 py-4 flex gap-4">
                     <AlertCircle className="h-5 w-5 text-yellow-500 flex-shrink-0 mt-0.5" />
                     <div>
                         <p className="text-slate-200 text-sm font-medium">Filler Words</p>
                         <p className="text-slate-400 text-xs mt-1">High usage of "um", "like", "basically" (14 times in 2 minutes).</p>
                     </div>
                 </div>
            </div>
        </div>

      </div>
    </div>
  );
};

export default Reports;
