import React from 'react';
import { ArrowLeft, Lock, Eye, Server, Shield } from 'lucide-react';
import { Button } from './ui/Button';

interface PrivacyPolicyProps {
  onBack: () => void;
}

export const PrivacyPolicy: React.FC<PrivacyPolicyProps> = ({ onBack }) => {
  return (
    <div className="min-h-screen bg-slate-50 py-12 px-4 sm:px-6 lg:px-8 font-sans">
      <div className="max-w-3xl mx-auto bg-white border border-slate-200 shadow-sm rounded-xl overflow-hidden">
        
        {/* Header */}
        <div className="px-8 py-6 border-b border-slate-100 flex justify-between items-center bg-slate-50/50">
          <div>
            <h1 className="text-2xl font-bold text-slate-900">Privacy Policy</h1>
            <p className="text-sm text-slate-500">Effective Date: October 2023</p>
          </div>
          <button onClick={onBack} className="text-slate-400 hover:text-slate-600">
            <ArrowLeft size={24} />
          </button>
        </div>

        <div className="p-8 space-y-8 text-slate-700 leading-relaxed text-sm">
          
          <p className="text-slate-600">
            At ZELVORA ("we", "our", "us"), we value your trust. This Privacy Policy explains how we collect, use, and protect your data when you use our AI interview evaluation platform.
          </p>

          {/* 1. Data Collection */}
          <section>
            <h2 className="text-base font-bold text-slate-900 mb-3 uppercase tracking-wide flex items-center gap-2">
              <Server size={16} className="text-blue-600" /> 1. Data We Collect
            </h2>
            <p className="mb-2">To provide interview evaluations, we collect and process the following:</p>
            <ul className="list-disc list-inside space-y-1 ml-2 text-slate-600">
              <li><strong>Account Information:</strong> Name, email address, and login credentials.</li>
              <li><strong>Professional Data:</strong> Resume content (text extracted from PDF) and job role preferences.</li>
              <li><strong>Interview Data:</strong> Audio responses, transcriptions, and behavioral metadata (e.g., eye contact scores, focus alerts).</li>
              <li><strong>Payment Metadata:</strong> Transaction IDs and payment status (via Razorpay). We do <strong>not</strong> store card details.</li>
            </ul>
          </section>

          {/* 2. Camera & Audio Usage */}
          <section className="bg-slate-50 border border-slate-200 p-4 rounded-lg">
            <h2 className="text-base font-bold text-slate-900 mb-3 uppercase tracking-wide flex items-center gap-2">
              <Eye size={16} className="text-blue-600" /> 2. Camera & Audio Usage
            </h2>
            <p className="mb-3">
              We use your device's camera and microphone strictly for the purpose of conducting the interview simulation.
            </p>
            <div className="grid md:grid-cols-2 gap-4">
               <div>
                  <h4 className="font-bold text-slate-900 mb-1">Camera</h4>
                  <p className="text-xs text-slate-600">Used to analyze visual presence (e.g., eye contact). Video streams are processed in real-time and are <strong>NOT recorded or stored</strong> on our servers.</p>
               </div>
               <div>
                  <h4 className="font-bold text-slate-900 mb-1">Microphone</h4>
                  <p className="text-xs text-slate-600">Used to capture your spoken answers. Audio data is processed by our AI models to generate transcripts and evaluations.</p>
               </div>
            </div>
          </section>

          {/* 3. AI Disclosure */}
          <section>
            <h2 className="text-base font-bold text-slate-900 mb-3 uppercase tracking-wide">3. AI & Automated Decision Making</h2>
            <p className="mb-2">
              ZELVORA uses Artificial Intelligence (AI) to conduct interviews and generate evaluation reports.
            </p>
            <ul className="list-disc list-inside space-y-1 ml-2 text-slate-600">
              <li>The "Interviewer" is an AI agent, not a human.</li>
              <li>Scores, feedback, and "hiring verdicts" are generated by AI algorithms based on your performance.</li>
              <li>The system may automatically terminate an interview if it detects abuse or repeated integrity violations.</li>
            </ul>
          </section>

          {/* 4. Data Usage */}
          <section>
            <h2 className="text-base font-bold text-slate-900 mb-3 uppercase tracking-wide">4. How We Use Your Data</h2>
            <ul className="list-disc list-inside space-y-1 ml-2 text-slate-600">
              <li>To generate your Interview Report and Scorecard.</li>
              <li>To maintain your interview history and progress logs.</li>
              <li>To anonymously improve our evaluation models (aggregated data only).</li>
              <li>To prevent fraud and abuse of the platform.</li>
            </ul>
          </section>

          {/* 5. Data Sharing */}
          <section>
            <h2 className="text-base font-bold text-slate-900 mb-3 uppercase tracking-wide flex items-center gap-2">
               <Shield size={16} className="text-blue-600" /> 5. Data Sharing & Security
            </h2>
            <p className="mb-2">
               We do <strong>not</strong> sell your personal data. We do not share your resume or interview performance with third-party recruiters or companies.
            </p>
            <p className="mb-2">
               <strong>Service Providers:</strong> We use trusted third-party services for specific functions:
            </p>
            <ul className="list-disc list-inside space-y-1 ml-2 text-slate-600">
               <li><strong>Razorpay:</strong> For secure payment processing.</li>
               <li><strong>Google Cloud / AI:</strong> For hosting and AI model processing.</li>
            </ul>
          </section>

          {/* 6. User Rights */}
          <section>
            <h2 className="text-base font-bold text-slate-900 mb-3 uppercase tracking-wide">6. Your Rights</h2>
            <p className="mb-2">You have the right to:</p>
            <ul className="list-disc list-inside space-y-1 ml-2 text-slate-600">
               <li>Access your interview reports (subject to your subscription plan).</li>
               <li>Request deletion of your account and associated data.</li>
               <li>Contact us regarding privacy concerns.</li>
            </ul>
          </section>

          {/* Contact */}
          <section className="pt-4 border-t border-slate-100">
             <p className="text-slate-500 text-xs">
                If you have any questions about this policy, please contact us at <a href="mailto:privacy@zelvora.com" className="text-blue-600 underline">privacy@zelvora.com</a>.
             </p>
          </section>

        </div>

        <div className="bg-slate-50 p-6 border-t border-slate-200 text-center">
          <Button onClick={onBack}>Return to Dashboard</Button>
        </div>

      </div>
    </div>
  );
};